### PR TITLE
Updated to list props, and switched label in example to string 

### PR DESCRIPTION
**Pull request by danleveille**

### CODE REVIEW

**Comment by danleveille** [comment]
@mkko Any chance you could merge these PRs? Thanks! :)

**Comment by mkko** [comment]
Oh, thanks for pinging me! I've completely missed these changes.

**Comment by mkko** [comment]
Thank you for the contributions, and my sincerest apologies for not seeing this earlier 🙈

**Comment by danleveille** [comment]
@mkko No problem! Thanks for merging! 😄

**Pull request merged**
